/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import javax.swing.ScrollPaneConstants;
import Controlador.C_Operaciones;
import Modelo.Operaciones;
/**
 *
 * @author marcooo
 */
public class CalculadoraForm extends javax.swing.JFrame {
    Operaciones operandos = new Operaciones(0, 0);
    C_Operaciones controlador = new C_Operaciones(operandos);
    private boolean resultadoPrinted = false;
    
    public void setNumeros(int num){
         if(txaResultado.getText().equals("0")) {
            operandos.setA(num);
        } else if(operandos.getA()!=0){
            operandos.setB(num);
        }
    }
    
    public void separaYGuarda(){
        String texto = txaResultado.getText();
        char operador = ' ';
        
        if (texto.contains("+")) {
            operador = '+';
        } else if (texto.contains("-")) {
            operador = '-';
        } else if (texto.contains("*")) {
            operador = '*';
        } else if (texto.contains("/")) {
            operador = '/';
        }
        
        String[] partes = texto.split("\\" + operador); 
        // "\\+" si el operador es + (el doble backslash es necesario para regex)
        
        String parte1 = partes[0]; // "15"
        String parte2 = partes[1]; // "20"
        System.out.println(parte1+parte2+operador);
        
        int a = Integer.parseInt(parte1.trim());
        int b = Integer.parseInt(parte2.trim());

        operandos.setA(a);
        operandos.setB(b);
        
        double resultado = 0;
        switch (operador) {
            case '+': resultado = operandos.suma(); break;
            case '-': resultado = operandos.resta(); break;
            case '*': resultado = operandos.multiplicacion(); break;
            case '/': resultado = operandos.division(); break;
        }
        
         txaResultado.setText(String.format("%.1f", resultado));

    }
    public CalculadoraForm() {
        initComponents();
        txaResultado.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        execButton = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        division = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaResultado = new javax.swing.JTextArea();
        cleanbutton = new javax.swing.JButton();
        num10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        execButton.setText("EXEC");
        execButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                execButtonActionPerformed(evt);
            }
        });
        jPanel1.add(execButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 150, 91));

        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        jPanel1.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 57));

        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        jPanel1.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 70, 57));

        division.setText("/ ");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });
        jPanel1.add(division, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, 57));

        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        jPanel1.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 70, 51));

        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        jPanel1.add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 70, 51));

        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        jPanel1.add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 80, 51));

        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        jPanel1.add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 70, 52));

        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        jPanel1.add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 70, 52));

        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        jPanel1.add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 80, 52));

        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        jPanel1.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 80, 57));

        suma.setText("+ ");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });
        jPanel1.add(suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, 57));

        resta.setText("- ");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });
        jPanel1.add(resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, 57));

        multi.setText("* ");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        jPanel1.add(multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, 57));

        jLabel1.setText("por: Marco Catro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, -1, -1));

        txaResultado.setColumns(20);
        txaResultado.setRows(5);
        jScrollPane2.setViewportView(txaResultado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 120));

        cleanbutton.setText("CLEAN");
        cleanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(cleanbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 350, -1));

        num10.setText("0");
        num10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num10ActionPerformed(evt);
            }
        });
        jPanel1.add(num10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 260, 52));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        if(!resultadoPrinted){
            int num = Integer.parseInt(num1.getText());
            controlador.llenatxA(txaResultado, num + "");
        }
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        if(!resultadoPrinted){
            int num = Integer.parseInt(num2.getText());
            controlador.llenatxA(txaResultado, num + "");
        }
    }//GEN-LAST:event_num2ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        if(!resultadoPrinted){
            int num = Integer.parseInt(num8.getText());
            controlador.llenatxA(txaResultado, num + "");
        }
    }//GEN-LAST:event_num8ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        if(!resultadoPrinted){
            int num = Integer.parseInt(num7.getText());
            controlador.llenatxA(txaResultado, num + "");
        }
    }//GEN-LAST:event_num7ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        if(!resultadoPrinted){
            int num = Integer.parseInt(num3.getText());
            controlador.llenatxA(txaResultado, num + "");
        }
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        if(!resultadoPrinted){
            int num = Integer.parseInt(num4.getText());
            controlador.llenatxA(txaResultado, num + "");
        }
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        if(!resultadoPrinted){
            int num = Integer.parseInt(num5.getText());
            controlador.llenatxA(txaResultado, num + "");
        }
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        if(!resultadoPrinted){
            int num = Integer.parseInt(num6.getText());
            controlador.llenatxA(txaResultado, num + "");
        }
    }//GEN-LAST:event_num6ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        if(!resultadoPrinted){
            int num = Integer.parseInt(num9.getText());
            controlador.llenatxA(txaResultado, num + "");
        }
    }//GEN-LAST:event_num9ActionPerformed

    private void cleanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanbuttonActionPerformed
        txaResultado.setText("0");
        txaResultado.setEditable(true);
        resultadoPrinted = false;
    }//GEN-LAST:event_cleanbuttonActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        if(txaResultado.getText().equals("0"))
        controlador.llenatxA(txaResultado, "0+");
    }//GEN-LAST:event_sumaActionPerformed

    private void execButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execButtonActionPerformed

        controlador.separaYGuarda(txaResultado);
        txaResultado.setEditable(false);
        resultadoPrinted = true;
        
    }//GEN-LAST:event_execButtonActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        if(txaResultado.getText().equals("0"))
        controlador.llenatxA(txaResultado, "0-");
    }//GEN-LAST:event_restaActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        if(txaResultado.getText().equals("0"))
        controlador.llenatxA(txaResultado, "0*");
    }//GEN-LAST:event_multiActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        if(txaResultado.getText().equals("0"))
        controlador.llenatxA(txaResultado, "0/");
    }//GEN-LAST:event_divisionActionPerformed

    private void num10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num10ActionPerformed
        if(!resultadoPrinted){
            int num = Integer.parseInt(num10.getText());
            controlador.llenatxA(txaResultado, num + "");
        }
    }//GEN-LAST:event_num10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleanbutton;
    private javax.swing.JButton division;
    private javax.swing.JButton execButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton multi;
    private javax.swing.JButton num1;
    private javax.swing.JButton num10;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton resta;
    private javax.swing.JButton suma;
    private javax.swing.JTextArea txaResultado;
    // End of variables declaration//GEN-END:variables
}
